using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering.Universal;

public class BreathingLight : MonoBehaviour
{
    public Light2D breathingLight; // B接到你的 Light2D 艄饨M件
    public float minIntensity = 0.5f; // 最小度
    public float maxIntensity = 2.0f; // 最大度
    public float breathSpeed = 1.0f; // 呼吸速度

    private float targetIntensity; // 目度

    void Start()
    {
        // O置初始目度樽钚度
        targetIntensity = minIntensity;
    }

    void Update()
    {
        // 使用 Mathf.PingPong 函翟谧钚度和最大度之g循h化
        targetIntensity = Mathf.PingPong(Time.time * breathSpeed, maxIntensity - minIntensity) + minIntensity;

        // ⒛度用到光源上
        breathingLight.intensity = targetIntensity;
    }
}
