using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ClickPlot : MonoBehaviour
{
    public List<GameObject> itemsToShow; // 存σ@示的目
    private int currentIndex = 0;
    private bool isCoolingDown = false;
    public float coolDown;
    private void Update()
    {
        // z查是否有c糨入且不在冷s中
        if (Input.GetMouseButtonDown(0) && !isCoolingDown)
        {
            StartCoroutine(PlayItemWithCooldown());
        }
    }

    // 播放目K添加冷srg
    private IEnumerator PlayItemWithCooldown()
    {
        isCoolingDown = true;
        ShowNextItem(); // 播放目

        yield return new WaitForSeconds(coolDown); // 冷srg

        isCoolingDown = false; // 冷sY束
    }

    // @示下一目
    private void ShowNextItem()
    {
        if (currentIndex < itemsToShow.Count)
        {
            itemsToShow[currentIndex].SetActive(true); // @示前索引的目
            currentIndex++;
        }
    }
}
