using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class HandRotation: MonoBehaviour
{
    public Transform clockCenter; // 指定r中心的Transform
    public float duration = 1.0f; // 旋D持mrg，以秒挝
    public float elapsedTime = 0.0f; // ^的rg
    public float startAngle = 0.0f; // _始r的角度
    public float targetAngle = 90.0f; // 目私嵌龋r旋D90度

    void Start()
    {
    }

    void Update()
    {
        
    }

    public IEnumerator RotationCoroutine()
    {
        elapsedTime = 0.0f;
        float startAngle = transform.eulerAngles.z; // 记录开始时的角度
        float endAngle = startAngle + targetAngle; // 计算结束时的目标角度
        while (elapsedTime < duration)
        {
            elapsedTime += Time.deltaTime; // 更新^的rg
            float currentAngle = Mathf.Lerp(startAngle, startAngle + targetAngle, elapsedTime / duration);
            transform.RotateAround(clockCenter.position, Vector3.forward, currentAngle - transform.eulerAngles.z);
            yield return null;
        }
        transform.eulerAngles = new Vector3(0, 0, endAngle);
    }
}
